shell /usr/bin/bash

font_family FiraCode Nerd Font
enable_audio_bell no

# Naviguer vers le terminal suivant
map ctrl+shift+l next_tab
map ctrl+tab next_tab

# Naviguer vers le terminal précédent
map ctrl+shift+h previous_tab
map ctrl+shift+tab previous_tab
