set -g mouse on 

# Utiliser tmux-256color pour un support complet des séquences terminales
set -g default-terminal "tmux-256color"

# Activer le support du TrueColor (24-bit) selon le terminal hôte
set -as terminal-overrides ",xterm*:Tc,foot*:Tc,st*:Tc"

# Transmettre les variables d'environnement du terminal hôte aux sessions tmux
set -ga update-environment " TERM_PROGRAM FOOT_SOCKET WINDOWID XAUTHORITY WAYLAND_DISPLAY"

set -g history-limit 10000

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

setw -g monitor-activity on
setw -g visual-activity on

# --- Raccourcis personnalisés ---
# Prefix + M : déplacer la fenêtre courante vers une autre session (prompt)
bind-key M command-prompt -p "Move window to session:" "move-window -t '%%'"

# --- Gestionnaire de plugins (TPM) ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible' # Exemple de plugin recommandé
set -g @plugin '2kabhishek/tmux2k'

set -g @tmux2k-theme 'onedark'
set -g @tmux2k-icons-only true
set -g @tmux2k-show-powerline false

set -g @tmux2k-left-plugins "session git cwd"
set -g @tmux2k-right-plugins "cpu ram time"

# Initialisation de TPM (Chemin XDG adapté)
run '~/.config/tmux/plugins/tpm/tpm'
